stack_name: cfn-lambda-benchmark
bucket_name: bkt-lambda-benchmark
log_retention_in_days: 7
iterations_lambdas: 5
iterations_code: 50
schedule_state: DISABLED
schedule_expression: cron(0 14 * * ? *)
step_functions_debug: false

memory_sizes:
  - 128
  - 256
  - 384
  - 512
  - 640
  - 768
  - 896
  - 1024
  - 1280
  - 1536
  - 1792
  - 2048
