[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aws-config = "0.56"
aws-smithy-http = "0.56"
aws-sdk-s3 = "0.33"
